### ISSUE TITLE
redefinition issue

### ISSUE THREAD

**Issue by chegewara** [tobozo/ESP32-Chimera-Core#7]
When log level is higher than NONE redefinition error occurs:

https://github.com/tobozo/ESP32-Chimera-Core/blob/master/src/utility/Sprite.cpp#L2181
https://github.com/tobozo/ESP32-Chimera-Core/blob/master/src/M5Display.cpp#L204

**Comment by tobozo** [comment]
whoops, thanks for the feedback, this quick fix came to mind https://github.com/tobozo/ESP32-Chimera-Core/pull/8
